use_frameworks!

platform :ios, '8.0'

target 'SeedCategory_Example' do
  pod 'SeedCategory', :path => '../'

  target 'SeedCategory_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
